---
abstract: 'An API for communicating with ElasticSearch'
author:
  - 'Clinton Gormley <drtech@cpan.org>'
build_requires:
  File::Temp: 0.22
  IO::Socket: 0
  POSIX: 0
  Test::Most: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ElasticSearch
provides:
  ElasticSearch:
    file: lib/ElasticSearch.pm
    version: 0.16
  ElasticSearch::Error:
    file: lib/ElasticSearch.pm
requires:
  Data::Dumper: 0
  Encode: 0
  HTTP::Request: 0
  JSON::XS: 0
  LWP::ConnCache: 0
  LWP::UserAgent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.16
