---
abstract: 'The official client for Elasticsearch'
author:
  - 'Clinton Gormley <drtech@cpan.org>'
build_requires:
  Exporter: 0
  File::Basename: 0
  Log::Any::Adapter::Callback: 0
  Test::Deep: 0
  Test::Exception: 0
  Test::More: 0.98
  YAML: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Elasticsearch
recommends:
  JSON::XS: 0
  URI::Escape::XS: 0
requires:
  Any::URI::Escape: 0
  Data::Dumper: 0
  Encode: 0
  HTTP::Tiny: v0.33.0
  IO::Select: 0
  IO::Socket::SSL: 0
  IO::Uncompress::Inflate: 0
  JSON: 0
  List::Util: 0
  Log::Any: 0
  Log::Any::Adapter: 0
  MIME::Base64: 0
  Module::Runtime: 0
  Moo: 0
  Moo::Role: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  Time::HiRes: 0
  Try::Tiny: 0
  URI: 0
  namespace::autoclean: 0
  overload: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/elasticsearch/elasticsearch-perl/issues
  repository: git://github.com/elasticsearch/elasticsearch-perl.git
version: 0.71
