---
abstract: 'The official client for Elasticsearch (beta)'
author:
  - 'Clinton Gormley <drtech@cpan.org>'
build_requires:
  File::Temp: 0.20
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.130880'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Elasticsearch
recommends:
  JSON::XS: 0
  URI::Escape::XS: 0
resources:
  bugtracker: https://github.com/elasticsearch/elasticsearch-perl/issues
  repository: git://github.com/elasticsearch/elasticsearch-perl.git
version: 0.70
